name: Release Library
# Job will only run on push to the main branch after the test job and release library job have passed

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "assets/**"
      - "demo/public/**"
      - "*.yml"
      - "*.json"
      - "*.config"
      - "*.md"
      - "!package.json"
  workflow_run:
    workflows: [ "Test Lib-Demo", "Release Library" ]
    types: [ completed ]

env:
  ARTIFACT_NAME: "build-demo-artifact"
  TIMEOUT_MINUTES: 2

permissions:
  contents: write # Required to publish to GitHub Pages
  packages: write # Required to publish to GitHub Pages
  id-token: write # Required to publish to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TIMEOUT_MINUTES }}
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js - Version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'yarn'

      - name: Create cache directories
        run: mkdir -p ~/.cache/yarn && mkdir -p ${{ github.workspace }}/.yarn

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ${{ github.workspace }}/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build demo
        run: |
          yarn gh-pages:build
          yarn gh-pages:copy404
          yarn gh-pages:postBuild

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ vars.DEMO_PATH }}
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TIMEOUT_MINUTES }}
    environment: github-pages
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ vars.DEMO_PATH }}

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ vars.DEMO_PATH }}
          publish_branch: gh-pages
          force_orphan: true
