name: Test Lib-Demo

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "assets/**"
      - "demo/public/**"
      - "*.yml"
      - "*.json"
      - "*.config"
      - "*.md"
  workflow_run:
    workflows: [ "Build Lib-Demo" ]
    types: [ completed ]
  workflow_dispatch:
    inputs: { }
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: FSI_DEP_NodeJs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js - Version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test Lint (Library)
        run: yarn lint:lib

      - name: Test TypeScript (Library)
        run: yarn type-check:lib

      - name: Test Lint (Demo)
        run: yarn lint:demo

      - name: Test TypeScript (Demo)
        run: yarn type-check:demo

      - name: Test library
        run: yarn test:ci_cd
